/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Huffman.View;

import fitos_games.Home;
import java.awt.Color;

/**
 *
 * @author malith
 */
public class HuffmanMenu extends javax.swing.JFrame {

    /**
     * Creates new form HuffmanMenu
     */
    public HuffmanMenu() {
        initComponents();
        this.setTitle("Huffman Encode Decode Game Menu");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStringToEncode = new fitos_games.LableRound();
        btnEncodeToString = new fitos_games.LableRound();
        btnExit = new fitos_games.LableRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnStringToEncode.setBackground(new java.awt.Color(153, 153, 255));
        btnStringToEncode.setForeground(new java.awt.Color(255, 255, 255));
        btnStringToEncode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnStringToEncode.setText("String Encode");
        btnStringToEncode.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnStringToEncode.setRoundBottomLeft(60);
        btnStringToEncode.setRoundBottomRight(60);
        btnStringToEncode.setRoundTopLeft(60);
        btnStringToEncode.setRoundTopRight(60);
        btnStringToEncode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStringToEncodeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStringToEncodeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStringToEncodeMouseExited(evt);
            }
        });

        btnEncodeToString.setBackground(new java.awt.Color(153, 153, 255));
        btnEncodeToString.setForeground(new java.awt.Color(255, 255, 255));
        btnEncodeToString.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEncodeToString.setText("String Decode");
        btnEncodeToString.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEncodeToString.setRoundBottomLeft(60);
        btnEncodeToString.setRoundBottomRight(60);
        btnEncodeToString.setRoundTopLeft(60);
        btnEncodeToString.setRoundTopRight(60);
        btnEncodeToString.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEncodeToStringMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEncodeToStringMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEncodeToStringMouseExited(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 51, 0));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("Exit");
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnExit.setRoundBottomLeft(60);
        btnExit.setRoundBottomRight(60);
        btnExit.setRoundTopLeft(60);
        btnExit.setRoundTopRight(60);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStringToEncode, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEncodeToString, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(btnStringToEncode, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEncodeToString, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStringToEncodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStringToEncodeMouseClicked
        // TODO add your handling code here:
        HuffmanEncode he = new HuffmanEncode();
         he.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnStringToEncodeMouseClicked

    private void btnStringToEncodeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStringToEncodeMouseEntered
        // TODO add your handling code here:
         btnStringToEncode.setBackground(Color.white);
         btnStringToEncode.setForeground(Color.decode("#9999FF"));
    }//GEN-LAST:event_btnStringToEncodeMouseEntered

    private void btnStringToEncodeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStringToEncodeMouseExited
        // TODO add your handling code here:
        btnStringToEncode.setBackground(Color.decode("#9999FF"));
        btnStringToEncode.setForeground(Color.white);
    }//GEN-LAST:event_btnStringToEncodeMouseExited

    private void btnEncodeToStringMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncodeToStringMouseClicked
        // TODO add your handling code here:
        HuffmanDecode hd = new HuffmanDecode();
         hd.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnEncodeToStringMouseClicked

    private void btnEncodeToStringMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncodeToStringMouseEntered
        // TODO add your handling code here:
        btnEncodeToString.setBackground(Color.white);
         btnEncodeToString.setForeground(Color.decode("#9999FF"));
    }//GEN-LAST:event_btnEncodeToStringMouseEntered

    private void btnEncodeToStringMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncodeToStringMouseExited
        // TODO add your handling code here:
        btnEncodeToString.setBackground(Color.decode("#9999FF"));
        btnEncodeToString.setForeground(Color.white);
    }//GEN-LAST:event_btnEncodeToStringMouseExited

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        Home hm = new Home();
         hm.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
         btnExit.setBackground(Color.white);
         btnExit.setForeground(Color.decode("#FF3300"));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setBackground(Color.decode("#FF3300"));
        btnExit.setForeground(Color.white);
    }//GEN-LAST:event_btnExitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HuffmanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HuffmanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HuffmanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HuffmanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HuffmanMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fitos_games.LableRound btnEncodeToString;
    private fitos_games.LableRound btnExit;
    private fitos_games.LableRound btnStringToEncode;
    // End of variables declaration//GEN-END:variables
}
