/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Huffman.View;

import fitos_games.Home;
import java.awt.Color;

/**
 *
 * @author malith
 */
public class HuffmanEncode extends javax.swing.JFrame {

    /**
     * Creates new form HuffmanEncode
     */
    public HuffmanEncode() {
        initComponents();
        this.setTitle("Huffman String Encode Game");
  
       
    }
     
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStringValue = new javax.swing.JLabel();
        btnStringToEncodeCheck = new fitos_games.LableRound();
        txtStringToEncodAnswer = new javax.swing.JTextField();
        btnStringToEncodeSeeAnswer = new fitos_games.LableRound();
        btnExit = new fitos_games.LableRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(920, 448));
        setResizable(false);

        lblStringValue.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblStringValue.setForeground(new java.awt.Color(0, 0, 0));
        lblStringValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStringValue.setText("Value");
        lblStringValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnStringToEncodeCheck.setBackground(new java.awt.Color(153, 153, 255));
        btnStringToEncodeCheck.setForeground(new java.awt.Color(255, 255, 255));
        btnStringToEncodeCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnStringToEncodeCheck.setText("Check");
        btnStringToEncodeCheck.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnStringToEncodeCheck.setRoundBottomLeft(60);
        btnStringToEncodeCheck.setRoundBottomRight(60);
        btnStringToEncodeCheck.setRoundTopLeft(60);
        btnStringToEncodeCheck.setRoundTopRight(60);
        btnStringToEncodeCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStringToEncodeCheckMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStringToEncodeCheckMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStringToEncodeCheckMouseExited(evt);
            }
        });

        txtStringToEncodAnswer.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtStringToEncodAnswer.setForeground(new java.awt.Color(0, 0, 0));
        txtStringToEncodAnswer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStringToEncodAnswer.setText("Enter Your Answer");
        txtStringToEncodAnswer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtStringToEncodAnswer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtStringToEncodAnswerMouseClicked(evt);
            }
        });
        txtStringToEncodAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStringToEncodAnswerActionPerformed(evt);
            }
        });

        btnStringToEncodeSeeAnswer.setBackground(new java.awt.Color(102, 255, 102));
        btnStringToEncodeSeeAnswer.setForeground(new java.awt.Color(255, 255, 255));
        btnStringToEncodeSeeAnswer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnStringToEncodeSeeAnswer.setText("See Answer");
        btnStringToEncodeSeeAnswer.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnStringToEncodeSeeAnswer.setPreferredSize(new java.awt.Dimension(1000, 32));
        btnStringToEncodeSeeAnswer.setRoundBottomLeft(60);
        btnStringToEncodeSeeAnswer.setRoundBottomRight(60);
        btnStringToEncodeSeeAnswer.setRoundTopLeft(60);
        btnStringToEncodeSeeAnswer.setRoundTopRight(60);
        btnStringToEncodeSeeAnswer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStringToEncodeSeeAnswerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStringToEncodeSeeAnswerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStringToEncodeSeeAnswerMouseExited(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 51, 0));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("Exit");
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnExit.setRoundBottomLeft(60);
        btnExit.setRoundBottomRight(60);
        btnExit.setRoundTopLeft(60);
        btnExit.setRoundTopRight(60);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblStringValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtStringToEncodAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnStringToEncodeSeeAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(btnStringToEncodeCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStringValue, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStringToEncodeSeeAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStringToEncodAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnStringToEncodeCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnStringToEncodeCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStringToEncodeCheckMouseClicked
        // TODO add your handling code here:
         
    }//GEN-LAST:event_btnStringToEncodeCheckMouseClicked

    private void btnStringToEncodeCheckMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStringToEncodeCheckMouseEntered
        // TODO add your handling code here:
        btnStringToEncodeCheck.setBackground(Color.white);
        btnStringToEncodeCheck.setForeground(Color.decode("#9999FF"));
    }//GEN-LAST:event_btnStringToEncodeCheckMouseEntered

    private void btnStringToEncodeCheckMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStringToEncodeCheckMouseExited
        // TODO add your handling code here:
        btnStringToEncodeCheck.setBackground(Color.decode("#9999FF"));
        btnStringToEncodeCheck.setForeground(Color.white);
    }//GEN-LAST:event_btnStringToEncodeCheckMouseExited

    private void txtStringToEncodAnswerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtStringToEncodAnswerMouseClicked
        // TODO add your handling code here:
        txtStringToEncodAnswer.setText("");
             
    }//GEN-LAST:event_txtStringToEncodAnswerMouseClicked

    private void btnStringToEncodeSeeAnswerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStringToEncodeSeeAnswerMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnStringToEncodeSeeAnswerMouseClicked

    private void btnStringToEncodeSeeAnswerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStringToEncodeSeeAnswerMouseEntered
        // TODO add your handling code here:
        btnStringToEncodeSeeAnswer.setBackground(Color.white);
        btnStringToEncodeSeeAnswer.setForeground(Color.decode("#66FF66"));
    }//GEN-LAST:event_btnStringToEncodeSeeAnswerMouseEntered

    private void btnStringToEncodeSeeAnswerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStringToEncodeSeeAnswerMouseExited
        // TODO add your handling code here:
        btnStringToEncodeSeeAnswer.setBackground(Color.decode("#66FF66"));
        btnStringToEncodeSeeAnswer.setForeground(Color.white);
    }//GEN-LAST:event_btnStringToEncodeSeeAnswerMouseExited

    private void txtStringToEncodAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStringToEncodAnswerActionPerformed
        // TODO add your handling code here:
       
       
    }//GEN-LAST:event_txtStringToEncodAnswerActionPerformed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        HuffmanMenu hufman = new HuffmanMenu();
        hufman.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setBackground(Color.white);
        btnExit.setForeground(Color.decode("#FF3300"));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setBackground(Color.decode("#FF3300"));
        btnExit.setForeground(Color.white);
    }//GEN-LAST:event_btnExitMouseExited

  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HuffmanEncode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HuffmanEncode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HuffmanEncode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HuffmanEncode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HuffmanEncode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fitos_games.LableRound btnExit;
    private fitos_games.LableRound btnStringToEncodeCheck;
    private fitos_games.LableRound btnStringToEncodeSeeAnswer;
    private javax.swing.JLabel lblStringValue;
    private javax.swing.JTextField txtStringToEncodAnswer;
    // End of variables declaration//GEN-END:variables
}
