/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TicTacToe.View;

import TicTacToe.TicTacToeController;
import fitos_games.Home;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author malith
 */
public class TicTacToe extends javax.swing.JFrame {

    /**
     * Creates new form TicTacToe
     */
    public TicTacToe() {
        initComponents();
        this.setTitle("Tic Tac Toe Game");

    }

    char board[][] = new char[3][3];
    TicTacToeController tic = new TicTacToeController();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        A1 = new fitos_games.LableRound();
        A2 = new fitos_games.LableRound();
        A3 = new fitos_games.LableRound();
        B1 = new fitos_games.LableRound();
        B2 = new fitos_games.LableRound();
        B3 = new fitos_games.LableRound();
        C2 = new fitos_games.LableRound();
        C3 = new fitos_games.LableRound();
        C1 = new fitos_games.LableRound();
        btnReset = new fitos_games.LableRound();
        btnExit = new fitos_games.LableRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        A1.setBackground(new java.awt.Color(255, 255, 255));
        A1.setForeground(new java.awt.Color(255, 0, 51));
        A1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A1.setText(" ");
        A1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        A1.setRoundTopLeft(30);
        A1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                A1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                A1MouseExited(evt);
            }
        });

        A2.setBackground(new java.awt.Color(255, 255, 255));
        A2.setForeground(new java.awt.Color(153, 153, 255));
        A2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A2.setText(" ");
        A2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        A2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                A2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                A2MouseExited(evt);
            }
        });

        A3.setBackground(new java.awt.Color(255, 255, 255));
        A3.setForeground(new java.awt.Color(255, 0, 51));
        A3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A3.setText(" ");
        A3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        A3.setRoundTopRight(30);
        A3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                A3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                A3MouseExited(evt);
            }
        });

        B1.setBackground(new java.awt.Color(255, 255, 255));
        B1.setForeground(new java.awt.Color(255, 0, 51));
        B1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B1.setText(" ");
        B1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B1MouseExited(evt);
            }
        });

        B2.setBackground(new java.awt.Color(255, 255, 255));
        B2.setForeground(new java.awt.Color(255, 0, 51));
        B2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B2.setText(" ");
        B2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B2MouseExited(evt);
            }
        });

        B3.setBackground(new java.awt.Color(255, 255, 255));
        B3.setForeground(new java.awt.Color(153, 153, 255));
        B3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B3.setText(" ");
        B3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        B3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B3MouseExited(evt);
            }
        });

        C2.setBackground(new java.awt.Color(255, 255, 255));
        C2.setForeground(new java.awt.Color(255, 0, 51));
        C2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C2.setText(" ");
        C2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        C2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                C2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                C2MouseExited(evt);
            }
        });

        C3.setBackground(new java.awt.Color(255, 255, 255));
        C3.setForeground(new java.awt.Color(255, 0, 51));
        C3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C3.setText(" ");
        C3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        C3.setRoundBottomRight(30);
        C3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                C3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                C3MouseExited(evt);
            }
        });

        C1.setBackground(new java.awt.Color(255, 255, 255));
        C1.setForeground(new java.awt.Color(153, 153, 255));
        C1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C1.setText(" ");
        C1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        C1.setRoundBottomLeft(30);
        C1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                C1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                C1MouseExited(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(153, 153, 255));
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReset.setText("Reset");
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnReset.setRoundBottomLeft(50);
        btnReset.setRoundBottomRight(50);
        btnReset.setRoundTopLeft(50);
        btnReset.setRoundTopRight(50);
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnResetMouseExited(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 51, 0));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("Exit");
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnExit.setRoundBottomLeft(50);
        btnExit.setRoundBottomRight(50);
        btnExit.setRoundTopLeft(50);
        btnExit.setRoundTopRight(50);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Player");

        jLabel2.setBackground(new java.awt.Color(187, 187, 187));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(A3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void A1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A1MouseEntered
        // TODO add your handling code here:
        A1.setBackground(Color.decode("#FFFF00"));
    }//GEN-LAST:event_A1MouseEntered

    private void A1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A1MouseExited
        // TODO add your handling code here:
        A1.setBackground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_A1MouseExited

    private void A1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A1MouseClicked
        // TODO add your handling code here:
        if (A1.getText().equals(" ")) {
            String win = tic.play(0, 0);
            setBoard();
            isGameOver(win);
        }
    }//GEN-LAST:event_A1MouseClicked

    private void A2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A2MouseEntered
        // TODO add your handling code here:
        A2.setBackground(Color.decode("#FFFF00"));
    }//GEN-LAST:event_A2MouseEntered

    private void A2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A2MouseExited
        // TODO add your handling code here:
        A2.setBackground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_A2MouseExited

    private void A2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A2MouseClicked
        // TODO add your handling code here:
        if (A2.getText().equals(" ")) {
            String win = tic.play(0, 1);            
            setBoard();
            isGameOver(win);
        }
    }//GEN-LAST:event_A2MouseClicked

    private void A3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A3MouseEntered
        // TODO add your handling code here:
        A3.setBackground(Color.decode("#FFFF00"));
    }//GEN-LAST:event_A3MouseEntered

    private void A3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A3MouseExited
        // TODO add your handling code here:
        A3.setBackground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_A3MouseExited

    private void A3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A3MouseClicked
        // TODO add your handling code here:
        if (A3.getText().equals(" ")) {
            //A1.setText("X");
            String win = tic.play(0, 2);
            setBoard();
            isGameOver(win);
        }
    }//GEN-LAST:event_A3MouseClicked

    private void B1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseEntered
        // TODO add your handling code here:
        B1.setBackground(Color.decode("#FFFF00"));
    }//GEN-LAST:event_B1MouseEntered

    private void B1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseExited
        // TODO add your handling code here:
        B1.setBackground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_B1MouseExited

    private void B1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseClicked
        // TODO add your handling code here:
        if (B1.getText().equals(" ")) {
            String win = tic.play(1, 0);
            setBoard();
            isGameOver(win);
        }
    }//GEN-LAST:event_B1MouseClicked

    private void B2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseEntered
        // TODO add your handling code here:
        B2.setBackground(Color.decode("#FFFF00"));
    }//GEN-LAST:event_B2MouseEntered

    private void B2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseExited
        // TODO add your handling code here:
        B2.setBackground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_B2MouseExited

    private void B2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseClicked
        // TODO add your handling code here:
        if (B2.getText().equals(" ")) {
            String win = tic.play(1, 1);
            setBoard();
            isGameOver(win);
        }
    }//GEN-LAST:event_B2MouseClicked

    private void B3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MouseEntered
        // TODO add your handling code here:
        B3.setBackground(Color.decode("#FFFF00"));
    }//GEN-LAST:event_B3MouseEntered

    private void B3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MouseExited
        // TODO add your handling code here:
        B3.setBackground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_B3MouseExited

    private void B3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MouseClicked
        // TODO add your handling code here:
        if (B3.getText().equals(" ")) {
            String win = tic.play(1, 2);
            setBoard();
            isGameOver(win);
        }
    }//GEN-LAST:event_B3MouseClicked

    private void C1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C1MouseEntered
        // TODO add your handling code here:
        C1.setBackground(Color.decode("#FFFF00"));
    }//GEN-LAST:event_C1MouseEntered

    private void C1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C1MouseExited
        // TODO add your handling code here:
        C1.setBackground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_C1MouseExited

    private void C1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C1MouseClicked
        // TODO add your handling code here:
        if (C1.getText().equals(" ")) {
            String win = tic.play(2, 0);
            setBoard();
            isGameOver(win);
        }
    }//GEN-LAST:event_C1MouseClicked

    private void C2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C2MouseEntered
        // TODO add your handling code here:
        C2.setBackground(Color.decode("#FFFF00"));
    }//GEN-LAST:event_C2MouseEntered

    private void C2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C2MouseExited
        // TODO add your handling code here:
        C2.setBackground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_C2MouseExited

    private void C2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C2MouseClicked
        // TODO add your handling code here:
        if (C2.getText().equals(" ")) {
            String win = tic.play(2, 1);
            setBoard();
            isGameOver(win);
        }
    }//GEN-LAST:event_C2MouseClicked

    private void C3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C3MouseEntered
        // TODO add your handling code here:
        C3.setBackground(Color.decode("#FFFF00"));
    }//GEN-LAST:event_C3MouseEntered

    private void C3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C3MouseExited
        // TODO add your handling code here:
        C3.setBackground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_C3MouseExited

    private void C3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C3MouseClicked
        // TODO add your handling code here:
        if (C3.getText().equals(" ")) {
            String win = tic.play(2, 2);
            setBoard();
            isGameOver(win);
        }
    }//GEN-LAST:event_C3MouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setBackground(Color.white);
        btnExit.setForeground(Color.decode("#FF3300"));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setBackground(Color.decode("#FF3300"));
        btnExit.setForeground(Color.white);
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        Home hm = new Home();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseEntered
        // TODO add your handling code here:
        btnReset.setBackground(Color.white);
        btnReset.setForeground(Color.decode("#9999FF"));
    }//GEN-LAST:event_btnResetMouseEntered

    private void btnResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseExited
        // TODO add your handling code here:
        btnReset.setBackground(Color.decode("#9999FF"));
        btnReset.setForeground(Color.white);
    }//GEN-LAST:event_btnResetMouseExited

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        // TODO add your handling code here:
        new TicTacToe().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnResetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fitos_games.LableRound A1;
    private fitos_games.LableRound A2;
    private fitos_games.LableRound A3;
    private fitos_games.LableRound B1;
    private fitos_games.LableRound B2;
    private fitos_games.LableRound B3;
    private fitos_games.LableRound C1;
    private fitos_games.LableRound C2;
    private fitos_games.LableRound C3;
    private fitos_games.LableRound btnExit;
    private fitos_games.LableRound btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private void setBoard() {
        char board[][] = new char[3][3];
        board = tic.getBoard();
        /// setting AI
        if (board[0][0] == 'O') {
            A1.setForeground(Color.decode("#9999FF"));
            A1.setText("O");
        }
        if (board[0][1] == 'O') {
            A2.setForeground(Color.decode("#9999FF"));
            A2.setText("O");
        }
        if (board[0][2] == 'O') {
            A3.setForeground(Color.decode("#9999FF"));
            A3.setText("O");
        }
        if (board[1][0] == 'O') {
            B1.setForeground(Color.decode("#9999FF"));
            B1.setText("O");
        }
        if (board[1][1] == 'O') {
            B2.setForeground(Color.decode("#9999FF"));
            B2.setText("O");
        }
        if (board[1][2] == 'O') {
            B3.setForeground(Color.decode("#9999FF"));
            B3.setText("O");
        }
        if (board[2][0] == 'O') {
            C1.setForeground(Color.decode("#9999FF"));
            C1.setText("O");
        }
        if (board[2][1] == 'O') {
            C2.setForeground(Color.decode("#9999FF"));
            C2.setText("O");
        }
        if (board[2][2] == 'O') {
            C3.setForeground(Color.decode("#9999FF"));
            C3.setText("O");
        }

        //Setting human
        if (board[0][0] == 'X') {
            A1.setForeground(Color.decode("#FF0033"));
            A1.setText("X");
        }
        if (board[0][1] == 'X') {
            A2.setForeground(Color.decode("#FF0033"));
            A2.setText("X");
        }
        if (board[0][2] == 'X') {
            A3.setForeground(Color.decode("#FF0033"));
            A3.setText("X");
        }
        if (board[1][0] == 'X') {
            B1.setForeground(Color.decode("#FF0033"));
            B1.setText("X");
        }
        if (board[1][1] == 'X') {
            B2.setForeground(Color.decode("#FF0033"));
            B2.setText("X");
        }
        if (board[1][2] == 'X') {
            B3.setForeground(Color.decode("#FF0033"));
            B3.setText("X");
        }
        if (board[2][0] == 'X') {
            C1.setForeground(Color.decode("#FF0033"));
            C1.setText("X");
        }
        if (board[2][1] == 'X') {
            C2.setForeground(Color.decode("#FF0033"));
            C2.setText("X");
        }
        if (board[2][2] == 'X') {
            C3.setForeground(Color.decode("#FF0033"));
            C3.setText("X");
        }
    }

    private void isGameOver(String win) {
        if (win.equals("HUMAN")) {
            JOptionPane.showMessageDialog(this, "Congradulations You Won The Game", "Wow...",  JOptionPane.INFORMATION_MESSAGE);
        }
        if (win.equals("AI")) {
            JOptionPane.showMessageDialog(this, "You Loose The Game Better Luck Next Time", "Oops...",  JOptionPane.INFORMATION_MESSAGE);
        }
        if (win.equals("DRAW")) {
            JOptionPane.showMessageDialog(this, "It's a Draw Let's Play Again", "Info...",  JOptionPane.INFORMATION_MESSAGE);
        }
    }
}
